### ISSUE TITLE
Automatically fetch drivers 

### ISSUE THREAD

**Issue by sortedcord** [sortedcord/udemy-web-scraper#14]
Setup a way to automatically fetch browser drivers based on user's choice (chromium/firefox) corresponding to the installed browser version.

The hard part will be to find the version of the browser installed.

**Comment by flyingcakes85** [comment]
I suppose this is the packager's job and developers shouldn't be touching this at all. Applications should assume dependencies are present.

On *nix systems, packages are installed via the package manager shipped with the OS. For example, I got [this](https://aur.archlinux.org/packages/chromedriver/) package. Will a python library interact with a package manager - which varies depending upon the distribution.

For a "udemy web scraper" python library, fetching binaries is out of scope.

Not to forget, the [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy)

> Write programs that do one thing and do it well.

**Comment by sortedcord** [comment]
Got it.
